// <auto-generated />
namespace Exam.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class devisTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(devisTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101328453_devisTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
